# Generated by Django 5.0.3 on 2024-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bamako',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bko_habit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gao_habit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kidal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kidal_habit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Koulikoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Koulikoro_habit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mopti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mopti_habit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sikasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sikasso_habit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ségou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ségou_habit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timbuktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timbuktu_habit', models.IntegerField()),
            ],
        ),
    ]
