# Generated by Django 5.0.3 on 2024-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_region_rename_bko_habit_bamako_habitats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='habitats',
        ),
    ]
