# Generated by Django 5.0.3 on 2024-06-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_bamako_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
